### ISSUE TITLE
BTagAnalyzer ttbar_metpt

### ISSUE THREAD

**Issue by fojensen** [cms-btv-pog/RecoBTag-PerformanceMeasurements#121]
I am interested in using the MET variables available in the BTagAnalyzer ntuples:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/BTagAnalyzer.cc#L1446-L1449
and noticed that the value of -10 is actually assigned to ttbar_metpt and ttbar_metphi for some events, meaning these are events with selMETs of zero size.
If instead of the default parametrized token:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/BTagAnalyzer.cc#L592
I use "slimmedMETS", I am able to recover all the events and see a "normal" MET distribution. I attached plots for demonstration. 

Is this known? What is the motivation?
Thank You

<img width="442" alt="screen shot 2019-02-03 at 6 57 16 pm" src="https://user-images.githubusercontent.com/6392809/52188101-a32adc80-27e5-11e9-9b5f-ab2fbc021a45.png">
<img width="449" alt="screen shot 2019-02-03 at 6 54 32 pm" src="https://user-images.githubusercontent.com/6392809/52188102-a4f4a000-27e5-11e9-9e11-648e3961ade9.png">

**Comment by rauser** [comment]
@fojensen sorry for coming back on this that late! I had a short look into the code, there are different possibilities for the token to be used for the MET collection. This depends for example on whether you use the ttbar filter or not. Could you point me to the configuration (or the pydump.py file) you used for producing these plots? Then I'll try to locate the origin of the behavior. Thanks, Johann

**Comment by fojensen** [comment]
When you say there are different possible tokens, do you just mean the three different MET types in MINIAOD: slimmedMETs, slimmedMETsNoHF, slimmedMETsPuppi? As mentioned here:
https://twiki.cern.ch/CMSPublic/WorkBookMiniAOD2017#High_level_physics_objects
I would expect those to exist for all events (in 2017 at least) and would never need a default -10 initialization. 
Or does the BTagAnalyzer produce new MET-like variables?

**Comment by fojensen** [comment]
The configuration is pretty simple:

Turn on the TTbarFilter:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/test/runBTagAnalyzer_cfg.py#L113

Don't cut on anything:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/TTbarSelectionFilter_cfi.py#L6

Store the ttbar variables:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/varGroups_cfi.py#L239

only run on 100 events:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/test/runBTagAnalyzer_cfg.py#L335

run:
cmsRun test/runBTagAnalyzer_cfg.py runOnData=False defaults=2017NewJEC


You can see there is a large contribution of -10 events.

**Comment by rauser** [comment]
Hey,
so I did some digging in the code and here is what I found out:
* The token's don't play a role for this behavior, when using MiniAOD, they are always set to slimmedMETs
* The negative entries are a result of the metCollection being cleared in the TTbarSelectionProducer, this happens at:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/TTbarSelectionProducer.cc#L369-L372
* This happens for events, that do not pass the defined selections of Leptons, Jets, and MET. As far as I can tell from my observations, it is always the jet selection that fails. This jet selection will always fail if no dilepton channel (chsel=0) can be assigned to the event or if there are not enough jets passing the jet selection, see https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/TTbarSelectionProducer.cc#L344-L345
* You can easily see what's going on by setting https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/TTbarSelectionProducer_cfi.py#L4 to a value of 6 or higher

Coming back to your original questions, whether this is known and what is the motivation. Well, it is known now :) Unfortunately I can't make a lot of statements about the motivation. This code hasn't been touched in quite a while and I also don't know, who's actually using these ttbar variables. But I assume that there has been a reason at some point for designing this producer that way. What is the confusing part in my opinion is the selectAll option in https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/TTbarSelectionFilter_cfi.py#L6 which doesn't result in the expected behavior of all events being selected...

**Comment by carolinecollard** [comment]
Hi Johann,

For the historical story, the code was put in place to do ttbar commissioning in the dilepton case in 2012. The idea was first to collect the information about electrons/muons/met in addition to the jets with the TTbarSelectionProduced, and then to decide what to store in the ntuple (TTbarSelectionFilter). The idea behind the selectAll was to have the possibility to store every events and then decide later what to do, especially interesting when working on MC events. 

Then the code was extended to treat also the commissioning for c-jet using semileptonic ttbar events. 

I think it was also used by the KIN and TwoTag methods, at least at the beginning. 

I don't know who is using it now. I suppose people involved in commissioning and performance studies using ttbar2l and ttbar1. 

Cheers,
Caroline

**Comment by rauser** [comment]
Hi Caroline,

thanks a lot for this information! I think it would be a good idea then to extend the code in a way, that the selectAll option of the TTbarSelectionFilter gives the desired effect of all events being selected. I'll try to have a look into this next week.

Cheers, Johann

**Comment by rauser** [comment]
I found some time to do it right now :) 
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/commit/4e538f277a79fa4198500783aa8fbd7111d2fe49
Having this flag introduced, I'm closing the issue. If there are any further problems, please feel free to reopen it.
