### ISSUE TITLE
 consumes semantics

### ISSUE THREAD

**Issue by jpata** [cms-btv-pog/RecoBTag-PerformanceMeasurements#15]
New mandatory consumes semantics in 76X also affect the BTagAnalyzer, preventing it from running in recent IB-s.

Something like the following is needed everywhere:

```
-  vertexSrc = iConfig.getParameter<edm::InputTag>("vertexCollection");
+  vertexSrc{ consumes<reco::VertexCollection>(iConfig.getParameter<edm::InputTag>("vertexCollection")) },
```

**Comment by ferencek** [comment]
Indeed, changes like those in https://github.com/cms-sw/cmssw/pull/10794 will have to be added to the BTagAnalyzer code for it to work with CMSSW_7_6_X. Since CMSSW_7_6_X is not yet a production release, this is not a very high priority but since the changes should be compatible with CMSSW_7_4_X, it's better to implement this sooner than later.

**Comment by jpata** [comment]
as I rely on the BTagAnalyzer for all cMVAv2 checks, the testing of https://github.com/cms-sw/cmssw/pull/10197 is currently affected by this.

**Comment by ferencek** [comment]
Testing yes, but not the feature itself.

**Comment by ghost** [comment]
I'm addressing this in the 7_5_X branch

**Comment by ghost** [comment]
I close this issue, as the 75X version of the analyzer addresses it, and works fine also with 76X (tested on CMSSW_7_6_0_pre2).
